[tool.poetry]
name = "db-learn"
version = "0.1.0"
description = ""
authors = ["bulwark <noemail@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.29"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
